#服务器端口
server:
  port: 8200

#数据源配置
#spring:
#  datasource:
#    url: ${blade.datasource.prod.url}
#    username: ${blade.datasource.prod.username}
#    password: ${blade.datasource.prod.password}

spring:
  #排除DruidDataSourceAutoConfigure
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        master:
          url: jdbc:mysql://192.168.100.245:3306/g1brain_file
          username: root
          password: 123456
        slave:
          url: jdbc:mysql://127.0.0.1:3306/g1brain_file_slave
          username: root
          password: 123456
